export interface AdminUser {
  id: string;
  name: string;
  email: string;
  phone: string;
  role: 'buyer' | 'seller' | 'admin';
  status: 'active' | 'banned' | 'suspended';
  joinedDate: string;
  lastActive: string;
  totalListings?: number;
  totalEnquiries?: number;
  subscriptionPlan?: 'free' | 'basic' | 'pro';
  banReason?: string;
}

export const mockAdminUsers: AdminUser[] = [
  {
    id: 'USR-1001',
    name: 'Vikram Malhotra',
    email: 'vikram.malhotra@gmail.com',
    phone: '+91 98765 43210',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-11-12',
    lastActive: '5 mins ago',
    totalListings: 12,
    subscriptionPlan: 'pro',
  },
  {
    id: 'USR-1002',
    name: 'Priya Sharma',
    email: 'priya.sharma@outlook.com',
    phone: '+91 98123 45678',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-01-05',
    lastActive: '18 mins ago',
    totalEnquiries: 14,
  },
  {
    id: 'USR-1003',
    name: 'Rajesh Developers',
    email: 'contact@rajeshrealty.in',
    phone: '+91 97111 22334',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-08-20',
    lastActive: '1 hour ago',
    totalListings: 28,
    subscriptionPlan: 'pro',
  },
  {
    id: 'USR-1004',
    name: 'Ananya Roy',
    email: 'ananya.roy@yahoo.com',
    phone: '+91 96543 21098',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-02-14',
    lastActive: '2 hours ago',
    totalEnquiries: 6,
  },
  {
    id: 'USR-1005',
    name: 'Karan Mehta',
    email: 'karan.m@mehtarealty.com',
    phone: '+91 99887 76655',
    role: 'seller',
    status: 'suspended',
    joinedDate: '2025-10-01',
    lastActive: '1 day ago',
    totalListings: 4,
    subscriptionPlan: 'basic',
    banReason: 'Policy violation: Duplicate listings across multiple accounts',
  },
  {
    id: 'USR-1006',
    name: 'Siddharth Varma',
    email: 'siddharth.admin@estatehub.com',
    phone: '+91 91234 56789',
    role: 'admin',
    status: 'active',
    joinedDate: '2025-05-01',
    lastActive: 'Just now',
  },
  {
    id: 'USR-1007',
    name: 'Sneha Reddy',
    email: 'sneha.reddy@gmail.com',
    phone: '+91 98450 11223',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-03-01',
    lastActive: '3 hours ago',
    totalEnquiries: 8,
  },
  {
    id: 'USR-1008',
    name: 'Spam Broker Entity',
    email: 'fake.agent@spamdomain.net',
    phone: '+91 90000 12345',
    role: 'seller',
    status: 'banned',
    joinedDate: '2026-02-28',
    lastActive: '3 days ago',
    totalListings: 1,
    subscriptionPlan: 'free',
    banReason: 'Fraudulent property details and fake price estimates',
  },
  {
    id: 'USR-1009',
    name: 'Amitabh Gupta',
    email: 'amitabh.gupta@corp.in',
    phone: '+91 97654 32109',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-09-15',
    lastActive: '15 mins ago',
    totalListings: 9,
    subscriptionPlan: 'pro',
  },
  {
    id: 'USR-1010',
    name: 'Meera Deshmukh',
    email: 'meera.d@gmail.com',
    phone: '+91 98220 33445',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-01-22',
    lastActive: '6 hours ago',
    totalEnquiries: 22,
  },
  {
    id: 'USR-1011',
    name: 'Rohan Kapoor',
    email: 'rohan.kapoor@kapoorhomes.com',
    phone: '+91 99100 88776',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-12-05',
    lastActive: '30 mins ago',
    totalListings: 15,
    subscriptionPlan: 'pro',
  },
  {
    id: 'USR-1012',
    name: 'Kavita Nair',
    email: 'kavita.nair@hotmail.com',
    phone: '+91 94470 55667',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-02-01',
    lastActive: '4 hours ago',
    totalEnquiries: 5,
  },
  {
    id: 'USR-1013',
    name: 'Harish Chandra',
    email: 'harish.c@chandraprop.in',
    phone: '+91 93311 44556',
    role: 'seller',
    status: 'banned',
    joinedDate: '2025-11-20',
    lastActive: '1 week ago',
    totalListings: 2,
    subscriptionPlan: 'free',
    banReason: 'Repeated non-compliance with seller verification rules',
  },
  {
    id: 'USR-1014',
    name: 'Deepak Joshi',
    email: 'deepak.j@joshirealty.com',
    phone: '+91 98980 12345',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-07-10',
    lastActive: '45 mins ago',
    totalListings: 18,
    subscriptionPlan: 'pro',
  },
  {
    id: 'USR-1015',
    name: 'Neha Agarwal',
    email: 'neha.agarwal@gmail.com',
    phone: '+91 97170 99887',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-03-10',
    lastActive: '10 mins ago',
    totalEnquiries: 11,
  },
  {
    id: 'USR-1016',
    name: 'Aarav Patel',
    email: 'aarav.patel@patelestate.com',
    phone: '+91 98250 66778',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-10-18',
    lastActive: '1 hour ago',
    totalListings: 7,
    subscriptionPlan: 'basic',
  },
  {
    id: 'USR-1017',
    name: 'Super Admin Operational',
    email: 'admin@estatehub.com',
    phone: '+91 98000 00000',
    role: 'admin',
    status: 'active',
    joinedDate: '2025-01-01',
    lastActive: 'Just now',
  },
  {
    id: 'USR-1018',
    name: 'Divya Sundaram',
    email: 'divya.s@yahoo.co.in',
    phone: '+91 94440 22334',
    role: 'buyer',
    status: 'suspended',
    joinedDate: '2026-01-18',
    lastActive: '2 days ago',
    totalEnquiries: 3,
    banReason: 'Abusive language reported in buyer inquiry forms',
  },
  {
    id: 'USR-1019',
    name: 'Gaurav Bhatia',
    email: 'gaurav.b@bhatiabuilders.in',
    phone: '+91 98110 33445',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-06-25',
    lastActive: '20 mins ago',
    totalListings: 25,
    subscriptionPlan: 'pro',
  },
  {
    id: 'USR-1020',
    name: 'Pooja Hegde',
    email: 'pooja.hegde@outlook.com',
    phone: '+91 98860 44556',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-02-22',
    lastActive: '5 hours ago',
    totalEnquiries: 9,
  },
  {
    id: 'USR-1021',
    name: 'Manish Saxena',
    email: 'manish.saxena@saxenaprop.com',
    phone: '+91 99200 55667',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-08-05',
    lastActive: '12 mins ago',
    totalListings: 5,
    subscriptionPlan: 'basic',
  },
  {
    id: 'USR-1022',
    name: 'Tanya Sen',
    email: 'tanya.sen@gmail.com',
    phone: '+91 98300 77889',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-03-15',
    lastActive: '50 mins ago',
    totalEnquiries: 4,
  },
  {
    id: 'USR-1023',
    name: 'Alok Tripathi',
    email: 'alok.tripathi@tripathihomes.in',
    phone: '+91 94150 88990',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-11-01',
    lastActive: '2 hours ago',
    totalListings: 11,
    subscriptionPlan: 'pro',
  },
  {
    id: 'USR-1024',
    name: 'Shweta Kulkarni',
    email: 'shweta.k@kulkarnirealty.com',
    phone: '+91 98230 99001',
    role: 'seller',
    status: 'banned',
    joinedDate: '2025-09-30',
    lastActive: '2 weeks ago',
    totalListings: 0,
    subscriptionPlan: 'free',
    banReason: 'Copyright infringement on property photos',
  },
  {
    id: 'USR-1025',
    name: 'Nikhil Bose',
    email: 'nikhil.bose@gmail.com',
    phone: '+91 98310 11223',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-02-10',
    lastActive: '1 hour ago',
    totalEnquiries: 17,
  },
  {
    id: 'USR-1026',
    name: 'Ritu Chaudhary',
    email: 'ritu.c@chaudharybuilders.com',
    phone: '+91 98180 22334',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-12-12',
    lastActive: '4 hours ago',
    totalListings: 14,
    subscriptionPlan: 'pro',
  },
  {
    id: 'USR-1027',
    name: 'Tarun Singh',
    email: 'tarun.singh@yahoo.com',
    phone: '+91 97180 33445',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-03-05',
    lastActive: '3 hours ago',
    totalEnquiries: 2,
  },
  {
    id: 'USR-1028',
    name: 'Archana Menon',
    email: 'archana.menon@menongroup.in',
    phone: '+91 94471 44556',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-10-10',
    lastActive: '25 mins ago',
    totalListings: 8,
    subscriptionPlan: 'basic',
  },
  {
    id: 'USR-1029',
    name: 'Karthik Raja',
    email: 'karthik.raja@gmail.com',
    phone: '+91 98400 55667',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-01-30',
    lastActive: '8 hours ago',
    totalEnquiries: 19,
  },
  {
    id: 'USR-1030',
    name: 'Bhavna Dave',
    email: 'bhavna.dave@daveproperties.com',
    phone: '+91 98251 66778',
    role: 'seller',
    status: 'active',
    joinedDate: '2025-07-28',
    lastActive: '10 mins ago',
    totalListings: 21,
    subscriptionPlan: 'pro',
  },
  {
    id: 'USR-1031',
    name: 'Varun Grover',
    email: 'varun.grover@groverrealty.in',
    phone: '+91 98101 77889',
    role: 'seller',
    status: 'suspended',
    joinedDate: '2025-11-25',
    lastActive: '1 day ago',
    totalListings: 3,
    subscriptionPlan: 'basic',
    banReason: 'Unresponsive to buyer inquiries for 14+ days',
  },
  {
    id: 'USR-1032',
    name: 'Ishita Dutta',
    email: 'ishita.dutta@outlook.com',
    phone: '+91 98301 88990',
    role: 'buyer',
    status: 'active',
    joinedDate: '2026-03-18',
    lastActive: '15 mins ago',
    totalEnquiries: 7,
  },
];
