import { Property } from '@/types/property';

export const mockProperties: Property[] = [
  {
    id: 'prop-1',
    title: '3 BHK Premium Apartment in DLF Phase 5',
    description: 'A spacious 3 BHK luxury apartment with modern amenities, large balconies, and scenic views of the city skyline.',
    price: 24500000, // 2.45 Cr
    currency: 'INR',
    type: 'sale',
    propertyType: 'apartment',
    bedrooms: 3,
    bathrooms: 3,
    area: 1850,
    areaUnit: 'sqft',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      address: 'Golf Course Road',
      city: 'Gurugram',
      state: 'Haryana',
      zipCode: '122002',
      coordinates: {
        lat: 28.4595,
        lng: 77.0266,
      },
    },
    amenities: [
      { id: '1', name: 'Gym', icon: 'Dumbbell' },
      { id: '2', name: 'Swimming Pool', icon: 'Waves' },
      { id: '3', name: 'Power Backup', icon: 'Zap' },
    ],
    status: 'available',
    featured: true,
    isVerified: true,
    createdAt: '2026-05-15T08:30:00Z',
    agent: {
      id: 'agent-1',
      name: 'Rajesh Kumar',
      email: 'rajesh@estatex.com',
      phone: '+91 98765 43210',
    },
  },
  {
    id: 'prop-2',
    title: '4 BHK Ultra Luxury Villa',
    description: 'Exquisite independent villa featuring a private garden, double-height ceiling, and modular Italian kitchen.',
    price: 58000000, // 5.80 Cr
    currency: 'INR',
    type: 'sale',
    propertyType: 'house',
    bedrooms: 4,
    bathrooms: 5,
    area: 3600,
    areaUnit: 'sqft',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      address: 'Sainik Farms',
      city: 'New Delhi',
      state: 'Delhi',
      zipCode: '110062',
      coordinates: {
        lat: 28.5140,
        lng: 77.2330,
      },
    },
    amenities: [
      { id: '2', name: 'Swimming Pool', icon: 'Waves' },
      { id: '4', name: 'Private Garden', icon: 'Flower' },
      { id: '5', name: 'Modular Kitchen', icon: 'ChefHat' },
    ],
    status: 'available',
    featured: true,
    isVerified: true,
    createdAt: '2026-06-01T10:15:00Z',
    agent: {
      id: 'agent-2',
      name: 'Amit Sharma',
      email: 'amit@estatex.com',
      phone: '+91 99999 88888',
    },
  },
  {
    id: 'prop-3',
    title: '2 BHK Modern Flat near Sector 62',
    description: 'Cozy and well-connected 2 BHK flat ideal for working professionals. Walkable distance to metro station.',
    price: 7500000, // 75 Lac
    currency: 'INR',
    type: 'sale',
    propertyType: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    areaUnit: 'sqft',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      address: 'Sector 62',
      city: 'Noida',
      state: 'Uttar Pradesh',
      zipCode: '201301',
      coordinates: {
        lat: 28.6273,
        lng: 77.3725,
      },
    },
    amenities: [
      { id: '3', name: 'Power Backup', icon: 'Zap' },
      { id: '6', name: '24x7 Security', icon: 'Shield' },
    ],
    status: 'available',
    featured: true,
    isVerified: false,
    createdAt: '2026-06-10T12:00:00Z',
    agent: {
      id: 'agent-1',
      name: 'Rajesh Kumar',
      email: 'rajesh@estatex.com',
      phone: '+91 98765 43210',
    },
  },
  {
    id: 'prop-4',
    title: 'Spacious Office Space in Hitech City',
    description: 'Fully furnished commercial office space with 45 workstations, 2 conference rooms, and pantry.',
    price: 120000, // 1.20 Lac/month
    currency: 'INR',
    type: 'rent',
    propertyType: 'commercial',
    bedrooms: 0,
    bathrooms: 2,
    area: 2400,
    areaUnit: 'sqft',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      address: 'Hitech City',
      city: 'Hyderabad',
      state: 'Telangana',
      zipCode: '500081',
      coordinates: {
        lat: 17.4483,
        lng: 78.3741,
      },
    },
    amenities: [
      { id: '7', name: 'High-speed Internet', icon: 'Wifi' },
      { id: '6', name: '24x7 Security', icon: 'Shield' },
      { id: '8', name: 'Pantry', icon: 'Coffee' },
    ],
    status: 'available',
    featured: true,
    isVerified: true,
    createdAt: '2026-06-12T09:00:00Z',
    agent: {
      id: 'agent-3',
      name: 'Kiran Reddy',
      email: 'kiran@estatex.com',
      phone: '+91 98888 77777',
    },
  },
  {
    id: 'prop-5',
    title: 'Residential Plot in Devanahalli',
    description: 'Ready-to-construct villa plot in a gated community near the International Airport.',
    price: 6500000, // 65 Lac
    currency: 'INR',
    type: 'sale',
    propertyType: 'land',
    bedrooms: 0,
    bathrooms: 0,
    area: 1500,
    areaUnit: 'sqft',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      address: 'Devanahalli',
      city: 'Bengaluru',
      state: 'Karnataka',
      zipCode: '562110',
      coordinates: {
        lat: 13.2500,
        lng: 77.7100,
      },
    },
    amenities: [
      { id: '9', name: 'Gated Community', icon: 'Fence' },
      { id: '10', name: 'Water Connection', icon: 'Droplet' },
    ],
    status: 'available',
    featured: true,
    isVerified: true,
    createdAt: '2026-06-05T14:45:00Z',
    agent: {
      id: 'agent-4',
      name: 'Suresh Gowda',
      email: 'suresh@estatex.com',
      phone: '+91 97777 66666',
    },
  },
  {
    id: 'prop-6',
    title: '3 BHK Luxury Apartment in Whitefield',
    description: 'Stunning 3 BHK apartment with premium woodwork, high-end electric fittings, and private terrace access.',
    price: 18500000, // 1.85 Cr
    currency: 'INR',
    type: 'sale',
    propertyType: 'apartment',
    bedrooms: 3,
    bathrooms: 3,
    area: 1950,
    areaUnit: 'sqft',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      address: 'Whitefield',
      city: 'Bengaluru',
      state: 'Karnataka',
      zipCode: '560066',
      coordinates: {
        lat: 12.9698,
        lng: 77.7499,
      },
    },
    amenities: [
      { id: '1', name: 'Gym', icon: 'Dumbbell' },
      { id: '2', name: 'Swimming Pool', icon: 'Waves' },
      { id: '11', name: 'Clubhouse', icon: 'PartyPopper' },
    ],
    status: 'available',
    featured: true,
    isVerified: true,
    createdAt: '2026-06-18T11:30:00Z',
    agent: {
      id: 'agent-4',
      name: 'Suresh Gowda',
      email: 'suresh@estatex.com',
      phone: '+91 97777 66666',
    },
  },
  {
    id: 'prop-7',
    title: '2 BHK Apartment for Rent in Gachibowli',
    description: 'Fully furnished 2 BHK apartment in a high-rise society. Ideal for IT professionals working in Gachibowli.',
    price: 38000, // 38k/month
    currency: 'INR',
    type: 'rent',
    propertyType: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    area: 1250,
    areaUnit: 'sqft',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      address: 'Gachibowli',
      city: 'Hyderabad',
      state: 'Telangana',
      zipCode: '500032',
      coordinates: {
        lat: 17.4401,
        lng: 78.3489,
      },
    },
    amenities: [
      { id: '1', name: 'Gym', icon: 'Dumbbell' },
      { id: '3', name: 'Power Backup', icon: 'Zap' },
      { id: '6', name: '24x7 Security', icon: 'Shield' },
    ],
    status: 'available',
    featured: true,
    isVerified: false,
    createdAt: '2026-06-20T08:00:00Z',
    agent: {
      id: 'agent-3',
      name: 'Kiran Reddy',
      email: 'kiran@estatex.com',
      phone: '+91 98888 77777',
    },
  },
  {
    id: 'prop-8',
    title: 'Premium Retail Shop in Connaught Place',
    description: 'Excellent commercial retail shop in a high-footfall zone. Ideal for brand outlets or premium restaurants.',
    price: 35000000, // 3.5 Cr
    currency: 'INR',
    type: 'sale',
    propertyType: 'commercial',
    bedrooms: 0,
    bathrooms: 1,
    area: 850,
    areaUnit: 'sqft',
    images: [
      'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&auto=format&fit=crop&q=80',
    ],
    location: {
      address: 'Connaught Place',
      city: 'New Delhi',
      state: 'Delhi',
      zipCode: '110001',
      coordinates: {
        lat: 28.6304,
        lng: 77.2177,
      },
    },
    amenities: [
      { id: '6', name: '24x7 Security', icon: 'Shield' },
      { id: '12', name: 'Central Air Conditioning', icon: 'AirVent' },
    ],
    status: 'available',
    featured: true,
    isVerified: true,
    createdAt: '2026-06-22T15:20:00Z',
    agent: {
      id: 'agent-2',
      name: 'Amit Sharma',
      email: 'amit@estatex.com',
      phone: '+91 99999 88888',
    },
  },
  {
    id: 'prop-9',
    title: '3 BHK Luxury Apartment in South Ext',
    description: 'Beautiful 3 BHK flat with spacious balconies, modular kitchen, and round-the-clock water supply.',
    price: 26000000,
    currency: 'INR',
    type: 'sale',
    propertyType: 'apartment',
    bedrooms: 3,
    bathrooms: 3,
    area: 1650,
    areaUnit: 'sqft',
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop&q=80'],
    location: {
      address: 'South Extension Part 2',
      city: 'New Delhi',
      state: 'Delhi',
      zipCode: '110049',
      coordinates: {
        lat: 28.5685,
        lng: 77.2215,
      },
    },
    amenities: [
      { id: '3', name: 'Power Backup', icon: 'Zap' },
      { id: '6', name: '24x7 Security', icon: 'Shield' },
    ],
    status: 'available',
    featured: false,
    isVerified: true,
    createdAt: '2026-06-21T09:30:00Z',
    agent: { id: 'agent-2', name: 'Amit Sharma', email: 'amit@estatex.com', phone: '+91 99999 88888' },
  },
  {
    id: 'prop-10',
    title: '1 BHK Cozy Apartment near Andheri East',
    description: 'Charming 1 BHK apartment situated in a peaceful locality. Close to the metro station and market.',
    price: 32000,
    currency: 'INR',
    type: 'rent',
    propertyType: 'apartment',
    bedrooms: 1,
    bathrooms: 1,
    area: 550,
    areaUnit: 'sqft',
    images: ['https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800&auto=format&fit=crop&q=80'],
    location: {
      address: 'J.B. Nagar, Andheri East',
      city: 'Mumbai',
      state: 'Maharashtra',
      zipCode: '400059',
      coordinates: {
        lat: 19.1155,
        lng: 72.8660,
      },
    },
    amenities: [
      { id: '3', name: 'Power Backup', icon: 'Zap' },
      { id: '13', name: 'Lift', icon: 'ArrowUpDown' },
    ],
    status: 'available',
    featured: false,
    isVerified: false,
    createdAt: '2026-06-22T10:15:00Z',
    agent: { id: 'agent-1', name: 'Rajesh Kumar', email: 'rajesh@estatex.com', phone: '+91 98765 43210' },
  },
  {
    id: 'prop-11',
    title: '2 BHK Modern Condo in Electronic City',
    description: 'Fully furnished 2 BHK apartment with high-speed internet, private parking, and swimming pool access.',
    price: 6800000,
    currency: 'INR',
    type: 'sale',
    propertyType: 'condo',
    bedrooms: 2,
    bathrooms: 2,
    area: 1050,
    areaUnit: 'sqft',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop&q=80'],
    location: {
      address: 'Phase 1, Electronic City',
      city: 'Bengaluru',
      state: 'Karnataka',
      zipCode: '560100',
      coordinates: {
        lat: 12.8452,
        lng: 77.6602,
      },
    },
    amenities: [
      { id: '2', name: 'Swimming Pool', icon: 'Waves' },
      { id: '7', name: 'High-speed Internet', icon: 'Wifi' },
    ],
    status: 'available',
    featured: false,
    isVerified: false,
    createdAt: '2026-06-23T11:00:00Z',
    agent: { id: 'agent-4', name: 'Suresh Gowda', email: 'suresh@estatex.com', phone: '+91 97777 66666' },
  },
  {
    id: 'prop-12',
    title: '3 BHK Sea-Facing Flat in Chennai',
    description: 'Luxurious 3 BHK flat with an unobstructed view of the beach, modular kitchen, and smart controls.',
    price: 75000,
    currency: 'INR',
    type: 'rent',
    propertyType: 'apartment',
    bedrooms: 3,
    bathrooms: 3,
    area: 1700,
    areaUnit: 'sqft',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80'],
    location: {
      address: 'Besant Nagar',
      city: 'Chennai',
      state: 'Tamil Nadu',
      zipCode: '600090',
      coordinates: {
        lat: 12.9975,
        lng: 80.2676,
      },
    },
    amenities: [
      { id: '2', name: 'Swimming Pool', icon: 'Waves' },
      { id: '6', name: '24x7 Security', icon: 'Shield' },
    ],
    status: 'available',
    featured: false,
    isVerified: false,
    createdAt: '2026-06-24T12:00:00Z',
    agent: { id: 'agent-2', name: 'Amit Sharma', email: 'amit@estatex.com', phone: '+91 99999 88888' },
  },
  {
    id: 'prop-13',
    title: '4 BHK Luxury Villa in Pune',
    description: 'Magnificent villa with private swimming pool, landscaped lawn, and personal elevator.',
    price: 38000000,
    currency: 'INR',
    type: 'sale',
    propertyType: 'house',
    bedrooms: 4,
    bathrooms: 4,
    area: 3200,
    areaUnit: 'sqft',
    images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&auto=format&fit=crop&q=80'],
    location: {
      address: 'Koregaon Park',
      city: 'Pune',
      state: 'Maharashtra',
      zipCode: '411001',
      coordinates: {
        lat: 18.5362,
        lng: 73.8930,
      },
    },
    amenities: [
      { id: '2', name: 'Swimming Pool', icon: 'Waves' },
      { id: '4', name: 'Private Garden', icon: 'Flower' },
    ],
    status: 'available',
    featured: false,
    isVerified: true,
    createdAt: '2026-06-25T13:00:00Z',
    agent: { id: 'agent-1', name: 'Rajesh Kumar', email: 'rajesh@estatex.com', phone: '+91 98765 43210' },
  },
  {
    id: 'prop-14',
    title: '3 BHK High-Rise Condo in Hyderabad',
    description: 'Premium flat on the 24th floor, offering spectacular panoramic city views and world-class amenities.',
    price: 19500000,
    currency: 'INR',
    type: 'sale',
    propertyType: 'condo',
    bedrooms: 3,
    bathrooms: 3,
    area: 2100,
    areaUnit: 'sqft',
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&auto=format&fit=crop&q=80'],
    location: {
      address: 'Jubilee Hills',
      city: 'Hyderabad',
      state: 'Telangana',
      zipCode: '500033',
      coordinates: {
        lat: 17.4312,
        lng: 78.4008,
      },
    },
    amenities: [
      { id: '1', name: 'Gym', icon: 'Dumbbell' },
      { id: '2', name: 'Swimming Pool', icon: 'Waves' },
    ],
    status: 'available',
    featured: false,
    isVerified: false,
    createdAt: '2026-06-25T14:30:00Z',
    agent: { id: 'agent-3', name: 'Kiran Reddy', email: 'kiran@estatex.com', phone: '+91 98888 77777' },
  },
  {
    id: 'prop-15',
    title: '2 BHK Premium Apartment for Rent',
    description: 'Fully furnished 2 BHK apartment with balcony overlooking a park. Secure gated community.',
    price: 45000,
    currency: 'INR',
    type: 'rent',
    propertyType: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    area: 1300,
    areaUnit: 'sqft',
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop&q=80'],
    location: {
      address: 'DLF Phase 4',
      city: 'Gurugram',
      state: 'Haryana',
      zipCode: '122002',
      coordinates: {
        lat: 28.4682,
        lng: 77.0822,
      },
    },
    amenities: [
      { id: '3', name: 'Power Backup', icon: 'Zap' },
      { id: '6', name: '24x7 Security', icon: 'Shield' },
    ],
    status: 'available',
    featured: false,
    isVerified: false,
    createdAt: '2026-06-26T09:00:00Z',
    agent: { id: 'agent-2', name: 'Amit Sharma', email: 'amit@estatex.com', phone: '+91 99999 88888' },
  },
  {
    id: 'prop-16',
    title: '5 BHK Heritage Bungalow in Kolkata',
    description: 'Spacious independent colonial-style bungalow with a large lawn, tall windows, and wooden floors.',
    price: 42000000,
    currency: 'INR',
    type: 'sale',
    propertyType: 'house',
    bedrooms: 5,
    bathrooms: 4,
    area: 3400,
    areaUnit: 'sqft',
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=80'],
    location: {
      address: 'Alipore',
      city: 'Kolkata',
      state: 'West Bengal',
      zipCode: '700027',
      coordinates: {
        lat: 22.5280,
        lng: 88.3280,
      },
    },
    amenities: [
      { id: '4', name: 'Private Garden', icon: 'Flower' },
      { id: '6', name: '24x7 Security', icon: 'Shield' },
    ],
    status: 'available',
    featured: false,
    isVerified: false,
    createdAt: '2026-06-26T11:00:00Z',
    agent: { id: 'agent-1', name: 'Rajesh Kumar', email: 'rajesh@estatex.com', phone: '+91 98765 43210' },
  },
  {
    id: 'prop-17',
    title: '2 BHK Sea-Link View Apartment',
    description: 'Beautifully designed 2 BHK flat overlooking the Bandra-Worli Sea Link. Prime location.',
    price: 95000,
    currency: 'INR',
    type: 'rent',
    propertyType: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    areaUnit: 'sqft',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop&q=80'],
    location: {
      address: 'Carter Road, Bandra West',
      city: 'Mumbai',
      state: 'Maharashtra',
      zipCode: '400050',
      coordinates: {
        lat: 19.0583,
        lng: 72.8215,
      },
    },
    amenities: [
      { id: '1', name: 'Gym', icon: 'Dumbbell' },
      { id: '6', name: '24x7 Security', icon: 'Shield' },
    ],
    status: 'available',
    featured: false,
    isVerified: false,
    createdAt: '2026-06-26T15:00:00Z',
    agent: { id: 'agent-3', name: 'Kiran Reddy', email: 'kiran@estatex.com', phone: '+91 98888 77777' },
  },
  {
    id: 'prop-18',
    title: '3 BHK Modern Flat in Dwarka',
    description: 'Well-ventilated 3 BHK flat with dedicated parking, power backup, and walking park nearby.',
    price: 16500000,
    currency: 'INR',
    type: 'sale',
    propertyType: 'apartment',
    bedrooms: 3,
    bathrooms: 3,
    area: 1550,
    areaUnit: 'sqft',
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80'],
    location: {
      address: 'Sector 10, Dwarka',
      city: 'New Delhi',
      state: 'Delhi',
      zipCode: '110075',
      coordinates: {
        lat: 28.5920,
        lng: 77.0460,
      },
    },
    amenities: [
      { id: '3', name: 'Power Backup', icon: 'Zap' },
      { id: '9', name: 'Gated Community', icon: 'Fence' },
    ],
    status: 'available',
    featured: false,
    isVerified: false,
    createdAt: '2026-06-27T08:30:00Z',
    agent: { id: 'agent-2', name: 'Amit Sharma', email: 'amit@estatex.com', phone: '+91 99999 88888' },
  },
  {
    id: 'prop-19',
    title: '1 BHK Cozy Flat in Indiranagar',
    description: 'Charming 1 BHK ideal for bachelor or young couple. Fully furnished and ready to move in.',
    price: 24000,
    currency: 'INR',
    type: 'rent',
    propertyType: 'apartment',
    bedrooms: 1,
    bathrooms: 1,
    area: 650,
    areaUnit: 'sqft',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop&q=80'],
    location: {
      address: 'Indiranagar',
      city: 'Bengaluru',
      state: 'Karnataka',
      zipCode: '560038',
      coordinates: {
        lat: 12.9784,
        lng: 77.6408,
      },
    },
    amenities: [
      { id: '3', name: 'Power Backup', icon: 'Zap' },
      { id: '7', name: 'High-speed Internet', icon: 'Wifi' },
    ],
    status: 'available',
    featured: false,
    isVerified: false,
    createdAt: '2026-06-27T10:00:00Z',
    agent: { id: 'agent-4', name: 'Suresh Gowda', email: 'suresh@estatex.com', phone: '+91 97777 66666' },
  },
  {
    id: 'prop-20',
    title: 'Modern Retail Space in Gachibowli',
    description: 'Premium glass-facade retail store situated in a highly populated software park zone.',
    price: 180000,
    currency: 'INR',
    type: 'rent',
    propertyType: 'commercial',
    bedrooms: 0,
    bathrooms: 2,
    area: 2800,
    areaUnit: 'sqft',
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80'],
    location: {
      address: 'Financial District, Gachibowli',
      city: 'Hyderabad',
      state: 'Telangana',
      zipCode: '500032',
      coordinates: {
        lat: 17.4250,
        lng: 78.3400,
      },
    },
    amenities: [
      { id: '6', name: '24x7 Security', icon: 'Shield' },
      { id: '7', name: 'High-speed Internet', icon: 'Wifi' },
    ],
    status: 'available',
    featured: false,
    isVerified: true,
    createdAt: '2026-06-27T12:00:00Z',
    agent: { id: 'agent-3', name: 'Kiran Reddy', email: 'kiran@estatex.com', phone: '+91 98888 77777' },
  },
  {
    id: 'prop-21',
    title: '3 BHK Spacious Flat in Hadapsar',
    description: 'Lovely 3 BHK flat with modern interiors, swimming pool access, and security.',
    price: 12500000,
    currency: 'INR',
    type: 'sale',
    propertyType: 'apartment',
    bedrooms: 3,
    bathrooms: 3,
    area: 1600,
    areaUnit: 'sqft',
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&auto=format&fit=crop&q=80'],
    location: {
      address: 'Hadapsar',
      city: 'Pune',
      state: 'Maharashtra',
      zipCode: '411028',
      coordinates: {
        lat: 18.5089,
        lng: 73.9259,
      },
    },
    amenities: [
      { id: '2', name: 'Swimming Pool', icon: 'Waves' },
      { id: '6', name: '24x7 Security', icon: 'Shield' },
    ],
    status: 'available',
    featured: false,
    isVerified: false,
    createdAt: '2026-06-27T14:00:00Z',
    agent: { id: 'agent-1', name: 'Rajesh Kumar', email: 'rajesh@estatex.com', phone: '+91 98765 43210' },
  },
  {
    id: 'prop-22',
    title: '2 BHK Flat for Sale in Adyar',
    description: 'Cozy and spacious 2 BHK apartment located in the prime area of Adyar. Modular kitchen.',
    price: 8800000,
    currency: 'INR',
    type: 'sale',
    propertyType: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    areaUnit: 'sqft',
    images: ['https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800&auto=format&fit=crop&q=80'],
    location: {
      address: 'Adyar',
      city: 'Chennai',
      state: 'Tamil Nadu',
      zipCode: '600020',
      coordinates: {
        lat: 13.0063,
        lng: 80.2574,
      },
    },
    amenities: [
      { id: '3', name: 'Power Backup', icon: 'Zap' },
      { id: '9', name: 'Gated Community', icon: 'Fence' },
    ],
    status: 'available',
    featured: false,
    isVerified: false,
    createdAt: '2026-06-28T09:30:00Z',
    agent: { id: 'agent-2', name: 'Amit Sharma', email: 'amit@estatex.com', phone: '+91 99999 88888' },
  },
  {
    id: 'prop-23',
    title: '3 BHK Flat for Rent in Salt Lake',
    description: 'Semi-furnished 3 BHK flat with lift, security guard, and covered car parking.',
    price: 32000,
    currency: 'INR',
    type: 'rent',
    propertyType: 'apartment',
    bedrooms: 3,
    bathrooms: 2,
    area: 1350,
    areaUnit: 'sqft',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80'],
    location: {
      address: 'Sector 3, Salt Lake',
      city: 'Kolkata',
      state: 'West Bengal',
      zipCode: '700091',
      coordinates: {
        lat: 22.5750,
        lng: 88.4200,
      },
    },
    amenities: [
      { id: '3', name: 'Power Backup', icon: 'Zap' },
      { id: '13', name: 'Lift', icon: 'ArrowUpDown' },
    ],
    status: 'available',
    featured: false,
    isVerified: false,
    createdAt: '2026-06-28T10:15:00Z',
    agent: { id: 'agent-1', name: 'Rajesh Kumar', email: 'rajesh@estatex.com', phone: '+91 98765 43210' },
  },
  {
    id: 'prop-24',
    title: 'Commercial Showroom for Sale',
    description: 'High visibility double-height showroom on the ground floor. Excellent foot traffic.',
    price: 45000000,
    currency: 'INR',
    type: 'sale',
    propertyType: 'commercial',
    bedrooms: 0,
    bathrooms: 2,
    area: 2100,
    areaUnit: 'sqft',
    images: ['https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&auto=format&fit=crop&q=80'],
    location: {
      address: 'MG Road',
      city: 'Gurugram',
      state: 'Haryana',
      zipCode: '122002',
      coordinates: {
        lat: 28.4795,
        lng: 77.0800,
      },
    },
    amenities: [
      { id: '6', name: '24x7 Security', icon: 'Shield' },
      { id: '12', name: 'Central Air Conditioning', icon: 'AirVent' },
    ],
    status: 'available',
    featured: false,
    isVerified: false,
    createdAt: '2026-06-28T12:00:00Z',
    agent: { id: 'agent-4', name: 'Suresh Gowda', email: 'suresh@estatex.com', phone: '+91 97777 66666' },
  },
  {
    id: 'prop-25',
    title: '4 BHK Luxury Penthouse in Worli',
    description: 'Stunning duplex penthouse featuring private terrace, deck pool, and bespoke woodwork.',
    price: 49500000,
    currency: 'INR',
    type: 'sale',
    propertyType: 'house',
    bedrooms: 4,
    bathrooms: 5,
    area: 3100,
    areaUnit: 'sqft',
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80'],
    location: {
      address: 'Worli Seaface',
      city: 'Mumbai',
      state: 'Maharashtra',
      zipCode: '400018',
      coordinates: {
        lat: 19.0250,
        lng: 72.8170,
      },
    },
    amenities: [
      { id: '2', name: 'Swimming Pool', icon: 'Waves' },
      { id: '4', name: 'Private Garden', icon: 'Flower' },
    ],
    status: 'available',
    featured: false,
    isVerified: true,
    createdAt: '2026-06-28T14:45:00Z',
    agent: { id: 'agent-3', name: 'Kiran Reddy', email: 'kiran@estatex.com', phone: '+91 98888 77777' },
  },
];
