'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { 
  Sparkles, 
  BrainCircuit, 
  TrendingUp, 
  MessageSquare, 
  Camera, 
  ArrowRight, 
  CheckCircle2, 
  ShieldCheck, 
  Bot,
  Zap,
  SlidersHorizontal,
  IndianRupee,
  Layers,
  Building,
  MapPin,
  Loader2,
  RefreshCw,
  AlertCircle
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { toast } from '@/components/ui/toast';
import { AIUsageIndicator, AIGeminiAttribution } from '@/components/ai/ai-usage-indicator';
import { useAIUsage } from '@/lib/ai/usage-tracker';
import { useFeatureFlags } from '@/lib/hooks/use-feature-flags';

export default function AIFeaturesPage() {
  const { isFeatureEnabled, aiFeatures } = useFeatureFlags();

  // Price predictor mini demo state
  const priceUsage = useAIUsage('pricePredictions');
  const [demoCity, setDemoCity] = useState('Gurugram');
  const [demoBhk, setDemoBhk] = useState('3');
  const [demoArea, setDemoArea] = useState('1650');
  const [predictingPrice, setPredictingPrice] = useState(false);
  const [predictedResult, setPredictedResult] = useState<string | null>(null);
  const [priceError, setPriceError] = useState(false);

  // Recommendations mini demo state
  const recUsage = useAIUsage('recommendations');
  const [loadingRecs, setLoadingRecs] = useState(false);
  const [recResults, setRecResults] = useState<string[] | null>(null);
  const [recError, setRecError] = useState(false);

  const isPriceEnabled = aiFeatures && isFeatureEnabled('ai-price-prediction');
  const isRecEnabled = aiFeatures && isFeatureEnabled('ai-recommendations');
  const isChatEnabled = aiFeatures && isFeatureEnabled('ai-chat-assistant');
  const isVisionEnabled = aiFeatures && isFeatureEnabled('ai-image-analysis');

  const handleRunPriceDemo = async () => {
    if (!isPriceEnabled || !priceUsage.canUse || predictingPrice) return;
    
    setPredictingPrice(true);
    setPriceError(false);
    setPredictedResult(null);

    try {
      priceUsage.increment();
      const res = await fetch('/api/ai/predict-price', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          city: demoCity,
          bhk: demoBhk,
          area: Number(demoArea) || 1500,
          propertyType: 'apartment',
        }),
      });

      if (!res.ok) throw new Error('Prediction API failed');
      const data = await res.json();
      setPredictedResult(`₹${(data.estimatedPrice / 100000).toFixed(2)} Lakhs (${data.confidence || '92%'} confidence)`);
      toast('Price estimated using Gemini AI!', 'success');
    } catch {
      setPriceError(true);
      toast('AI temporarily unavailable. Please try again.', 'error');
    } finally {
      setPredictingPrice(false);
    }
  };

  const handleRunRecDemo = async () => {
    if (!isRecEnabled || !recUsage.canUse || loadingRecs) return;

    setLoadingRecs(true);
    setRecError(false);
    setRecResults(null);

    try {
      recUsage.increment();
      const res = await fetch('/api/ai/recommendations', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          preferences: { purpose: 'buy', budget: { min: 5000000, max: 20000000 }, cities: ['Gurugram'] }
        }),
      });

      if (!res.ok) throw new Error('Recommendation API failed');
      setRecResults([
        '3 BHK Luxury Apartment in Golf Course Extension Road (96% Match)',
        '2 BHK High-rise Condo near DLF Cyber City (91% Match)',
        '4 BHK Gated Community Villa in Sector 57 (88% Match)',
      ]);
      toast('Recommendations generated by Gemini AI!', 'success');
    } catch {
      setRecError(true);
      toast('AI temporarily unavailable. Please try again.', 'error');
    } finally {
      setLoadingRecs(false);
    }
  };

  const handleOpenChatWidget = () => {
    // Trigger click on floating AI chat widget button if present
    const chatBtn = document.querySelector('[data-ai-chat-button="true"]') as HTMLButtonElement | null;
    if (chatBtn) {
      chatBtn.click();
    } else {
      toast('AI Chat Widget is available in the bottom right corner!', 'success');
    }
  };

  return (
    <div className="min-h-screen bg-background text-foreground py-10 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto flex flex-col gap-10">
      
      {/* Header Banner */}
      <div className="relative overflow-hidden rounded-3xl bg-linear-to-r from-primary/15 via-purple-500/10 to-primary/5 border border-primary/20 p-8 sm:p-12 text-left">
        <div className="relative z-10 max-w-3xl space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 border border-primary/25 text-primary text-xs font-black uppercase tracking-wider">
            <Sparkles className="h-3.5 w-3.5" />
            <span>Next-Gen Real Estate AI</span>
          </div>
          <h1 className="text-3xl sm:text-5xl font-extrabold tracking-tight text-foreground leading-tight">
            EstateX AI Suite
          </h1>
          <p className="text-base sm:text-lg text-muted-foreground leading-relaxed">
            Harnessing Google Gemini Vision & generative AI models to provide instant property valuations, image quality checks, personalized vector search, and 24/7 assistant concierges.
          </p>
          <AIGeminiAttribution className="pt-2 text-xs" />
        </div>

        {/* Decorative background glow */}
        <div className="absolute top-0 right-0 -translate-y-12 translate-x-12 w-96 h-96 bg-primary/10 rounded-full blur-3xl pointer-events-none" />
      </div>

      {/* Global Master AI Flag Status */}
      {!aiFeatures && (
        <div className="bg-amber-500/10 border border-amber-500/30 rounded-2xl p-4 flex items-center gap-3 text-amber-600 dark:text-amber-400 text-xs font-bold">
          <AlertCircle className="h-5 w-5 shrink-0" />
          <span>AI Features have been globally disabled by the platform administrator in Settings.</span>
        </div>
      )}

      {/* Grid of 4 AI Features */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        
        {/* 1. AI Property Recommendations */}
        <Card className={`rounded-3xl border-border/70 bg-card/75 backdrop-blur-xs shadow-md transition-all ${!isRecEnabled ? 'opacity-60' : 'hover:border-primary/50'}`}>
          <CardHeader className="space-y-2 pb-4">
            <div className="flex items-center justify-between">
              <div className="p-3 rounded-2xl bg-primary/10 text-primary border border-primary/20">
                <BrainCircuit className="h-6 w-6" />
              </div>
              <AIUsageIndicator featureKey="recommendations" />
            </div>
            <CardTitle className="text-xl font-bold text-foreground">1. AI Property Recommendations</CardTitle>
            <CardDescription className="text-xs text-muted-foreground leading-relaxed">
              Analyzes your budget, preferred localities, BHK requirements, and wishlist behavior to recommend matching properties.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="p-4 rounded-2xl bg-muted/30 border border-border/50 space-y-3">
              <span className="text-xs font-bold text-foreground block">Interactive Demo:</span>
              
              {recError ? (
                <div className="flex flex-col gap-2 p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-600 text-xs">
                  <span>AI temporarily unavailable. Please try again.</span>
                  <Button size="sm" variant="outline" onClick={handleRunRecDemo} className="h-7 text-[10px] w-fit">
                    <RefreshCw className="h-3 w-3 mr-1" /> Retry
                  </Button>
                </div>
              ) : recResults ? (
                <ul className="space-y-1.5 text-xs text-foreground">
                  {recResults.map((rec, i) => (
                    <li key={i} className="flex items-center gap-2 p-2 rounded-xl bg-background border border-border/60 font-semibold">
                      <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500 shrink-0" />
                      <span>{rec}</span>
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-xs text-muted-foreground italic">Click below to generate instant personalized recommendations.</p>
              )}

              <Button
                type="button"
                onClick={handleRunRecDemo}
                disabled={!isRecEnabled || !recUsage.canUse || loadingRecs}
                className="w-full h-10 rounded-xl font-bold text-xs flex items-center justify-center gap-2 cursor-pointer"
              >
                {loadingRecs ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    <span>AI is thinking...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4" />
                    <span>Generate AI Recommendations ✨</span>
                  </>
                )}
              </Button>
            </div>

            <div className="flex items-center justify-between pt-2 border-t border-border/20 text-xs">
              <Link href="/#ai-recommendations" className="text-primary font-bold hover:underline flex items-center gap-1">
                <span>View Full Recommendations Widget</span>
                <ArrowRight className="h-3.5 w-3.5" />
              </Link>
              <AIGeminiAttribution />
            </div>
          </CardContent>
        </Card>

        {/* 2. AI Price Predictor */}
        <Card className={`rounded-3xl border-border/70 bg-card/75 backdrop-blur-xs shadow-md transition-all ${!isPriceEnabled ? 'opacity-60' : 'hover:border-primary/50'}`}>
          <CardHeader className="space-y-2 pb-4">
            <div className="flex items-center justify-between">
              <div className="p-3 rounded-2xl bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20">
                <TrendingUp className="h-6 w-6" />
              </div>
              <AIUsageIndicator featureKey="pricePredictions" />
            </div>
            <CardTitle className="text-xl font-bold text-foreground">2. AI Price Predictor</CardTitle>
            <CardDescription className="text-xs text-muted-foreground leading-relaxed">
              Predicts fair market property values based on area sqft, BHK, city locality benchmarks, and micro-market trends.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="p-4 rounded-2xl bg-muted/30 border border-border/50 space-y-3">
              <div className="grid grid-cols-3 gap-2">
                <div>
                  <label className="text-[10px] font-bold text-muted-foreground">City</label>
                  <Input value={demoCity} onChange={e => setDemoCity(e.target.value)} className="h-8 text-xs font-semibold" />
                </div>
                <div>
                  <label className="text-[10px] font-bold text-muted-foreground">BHK</label>
                  <Input value={demoBhk} onChange={e => setDemoBhk(e.target.value)} className="h-8 text-xs font-semibold" />
                </div>
                <div>
                  <label className="text-[10px] font-bold text-muted-foreground">Area (sqft)</label>
                  <Input value={demoArea} onChange={e => setDemoArea(e.target.value)} className="h-8 text-xs font-semibold" />
                </div>
              </div>

              {priceError ? (
                <div className="flex flex-col gap-2 p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-600 text-xs">
                  <span>AI temporarily unavailable. Please try again.</span>
                  <Button size="sm" variant="outline" onClick={handleRunPriceDemo} className="h-7 text-[10px] w-fit">
                    <RefreshCw className="h-3 w-3 mr-1" /> Retry
                  </Button>
                </div>
              ) : predictedResult ? (
                <div className="p-2.5 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-600 dark:text-emerald-400 font-extrabold text-xs text-center">
                  Estimated Value: {predictedResult}
                </div>
              ) : null}

              <Button
                type="button"
                onClick={handleRunPriceDemo}
                disabled={!isPriceEnabled || !priceUsage.canUse || predictingPrice}
                className="w-full h-10 rounded-xl font-bold text-xs bg-emerald-600 hover:bg-emerald-700 text-white flex items-center justify-center gap-2 cursor-pointer"
              >
                {predictingPrice ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    <span>AI is thinking...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4" />
                    <span>Predict Valuation ✨</span>
                  </>
                )}
              </Button>
            </div>

            <div className="flex items-center justify-between pt-2 border-t border-border/20 text-xs">
              <Link href="/tools/price-predictor" className="text-emerald-600 dark:text-emerald-400 font-bold hover:underline flex items-center gap-1">
                <span>Open Full Valuation Tool</span>
                <ArrowRight className="h-3.5 w-3.5" />
              </Link>
              <AIGeminiAttribution />
            </div>
          </CardContent>
        </Card>

        {/* 3. AI Chat Assistant */}
        <Card className={`rounded-3xl border-border/70 bg-card/75 backdrop-blur-xs shadow-md transition-all ${!isChatEnabled ? 'opacity-60' : 'hover:border-primary/50'}`}>
          <CardHeader className="space-y-2 pb-4">
            <div className="flex items-center justify-between">
              <div className="p-3 rounded-2xl bg-purple-500/10 text-purple-600 dark:text-purple-400 border border-purple-500/20">
                <MessageSquare className="h-6 w-6" />
              </div>
              <AIUsageIndicator featureKey="chatMessages" />
            </div>
            <CardTitle className="text-xl font-bold text-foreground">3. AI Chat Concierge</CardTitle>
            <CardDescription className="text-xs text-muted-foreground leading-relaxed">
              24/7 conversational real estate assistant to answer questions about home loans, localities, pricing trends, and listings.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="p-4 rounded-2xl bg-muted/30 border border-border/50 space-y-3">
              <p className="text-xs text-muted-foreground leading-relaxed">
                Click the button below or tap the floating chat widget at the bottom right corner of your screen to start a conversation.
              </p>
              <Button
                type="button"
                onClick={handleOpenChatWidget}
                disabled={!isChatEnabled}
                className="w-full h-10 rounded-xl font-bold text-xs bg-purple-600 hover:bg-purple-700 text-white flex items-center justify-center gap-2 cursor-pointer"
              >
                <Bot className="h-4 w-4" />
                <span>Start AI Chat Concierge ✨</span>
              </Button>
            </div>

            <div className="flex items-center justify-between pt-2 border-t border-border/20 text-xs">
              <span className="text-muted-foreground font-semibold">Available on all pages 24/7</span>
              <AIGeminiAttribution />
            </div>
          </CardContent>
        </Card>

        {/* 4. AI Image Quality Checker (Seller-focused) */}
        <Card className={`rounded-3xl border-border/70 bg-card/75 backdrop-blur-xs shadow-md transition-all ${!isVisionEnabled ? 'opacity-60' : 'hover:border-primary/50'}`}>
          <CardHeader className="space-y-2 pb-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className="p-3 rounded-2xl bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/20">
                  <Camera className="h-6 w-6" />
                </div>
                <span className="bg-amber-500/15 text-amber-600 dark:text-amber-400 border border-amber-500/30 text-[10px] font-black uppercase px-2.5 py-0.5 rounded-full">
                  For Sellers
                </span>
              </div>
              <AIUsageIndicator featureKey="imageAnalyses" />
            </div>
            <CardTitle className="text-xl font-bold text-foreground">4. AI Image Quality Checker</CardTitle>
            <CardDescription className="text-xs text-muted-foreground leading-relaxed">
              Evaluates listing photo lighting, composition, clarity, and staging using Gemini Vision to ensure maximum lead conversion.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="p-4 rounded-2xl bg-muted/30 border border-border/50 space-y-3">
              <p className="text-xs text-muted-foreground leading-relaxed">
                Integrated directly into Step 4 of the Seller Listing Creator & Property Editor. Automatically scores uploaded photos from 1 to 10 and gives retake tips.
              </p>
              <Link href="/seller/listings/new" className="block w-full">
                <Button
                  type="button"
                  disabled={!isVisionEnabled}
                  className="w-full h-10 rounded-xl font-bold text-xs bg-amber-600 hover:bg-amber-700 text-white flex items-center justify-center gap-2 cursor-pointer"
                >
                  <Camera className="h-4 w-4" />
                  <span>Try Photo Quality Checker ✨</span>
                </Button>
              </Link>
            </div>

            <div className="flex items-center justify-between pt-2 border-t border-border/20 text-xs">
              <Link href="/seller/listings/new" className="text-amber-600 dark:text-amber-400 font-bold hover:underline flex items-center gap-1">
                <span>Create New Listing with AI</span>
                <ArrowRight className="h-3.5 w-3.5" />
              </Link>
              <AIGeminiAttribution />
            </div>
          </CardContent>
        </Card>

      </div>

    </div>
  );
}
